const db = require("./config/db");

const foods = [
    // BIRYANI
    ["Chicken Biryani", "Chicken Dum Biryani", 180],
    ["Chicken Biryani", "Chicken Biryani", 160],
    ["Chicken Biryani", "Boneless Chicken Biryani", 220],
    ["Chicken Biryani", "Chicken 65 Biryani", 220],
    ["Chicken Biryani", "Chicken Fry Piece Biryani", 220],
    ["Chicken Biryani", "Chicken Tikka Biryani", 230],
    ["Chicken Biryani", "Chicken Lollipop Biryani", 240],
    ["Chicken Biryani", "Chicken Ghee Roast Biryani", 230],
    ["Chicken Biryani", "Chicken Malai Tikka Biryani", 250],
    ["Chicken Biryani", "Special Chicken Biryani", 250],
    ["Chicken Biryani", "Andhra Chicken Biryani", 210],
    ["Chicken Biryani", "Achari Chicken Biryani", 210],
    ["Chicken Biryani", "Tandoori Chicken Biryani", 250],

    ["Mutton Biryani", "Mutton Dum Biryani", 280],
    ["Mutton Biryani", "Mutton Biryani", 270],
    ["Mutton Biryani", "Boneless Mutton Biryani", 320],
    ["Mutton Biryani", "Mutton Fry Piece Biryani", 320],
    ["Mutton Biryani", "Mutton Keema Biryani", 300],
    ["Mutton Biryani", "Mutton Ghee Roast Biryani", 320],
    ["Mutton Biryani", "Mutton Mughlai Biryani", 330],
    ["Mutton Biryani", "Special Mutton Biryani", 350],

    ["Egg Biryani", "Egg Biryani", 150],
    ["Egg Biryani", "Egg Masala Biryani", 170],
    ["Egg Biryani", "Egg Roast Biryani", 180],
    ["Egg Biryani", "Egg 65 Biryani", 190],

    ["Seafood Biryani", "Prawns Biryani", 280],
    ["Seafood Biryani", "Prawns Fry Biryani", 300],
    ["Seafood Biryani", "Fish Biryani", 280],
    ["Seafood Biryani", "Fish Fry Biryani", 300],

    ["Veg Biryani", "Veg Dum Biryani", 140],
    ["Veg Biryani", "Veg Biryani", 130],
    ["Veg Biryani", "Paneer Biryani", 170],
    ["Veg Biryani", "Paneer Tikka Biryani", 190],
    ["Veg Biryani", "Paneer 65 Biryani", 190],
    ["Veg Biryani", "Mushroom Biryani", 170],
    ["Veg Biryani", "Kaju Biryani", 190],
    ["Veg Biryani", "Kaju Paneer Biryani", 210],
    ["Veg Biryani", "Mixed Veg Biryani", 180],

    ["Special / Fusion", "Mixed Non-Veg Biryani", 350],
    ["Special / Fusion", "Chicken & Mutton Biryani", 380],
    ["Special / Fusion", "Chicken Kaju Biryani", 260],
    ["Special / Fusion", "Chicken Kaju Keema Biryani", 280],
    ["Special / Fusion", "Ulavacharu Chicken Biryani", 250],
    ["Special / Fusion", "Ulavacharu Mutton Biryani", 330],
    ["Special / Fusion", "Gongura Chicken Biryani", 240],
    ["Special / Fusion", "Gongura Mutton Biryani", 320],

    // DRINKS
    ["Soft Drinks", "Coke", 60],
    ["Soft Drinks", "Pepsi", 60],
    ["Soft Drinks", "Sprite", 60],
    ["Soft Drinks", "Fanta", 60],
    ["Soft Drinks", "Thums Up", 60],
    ["Soft Drinks", "Limca", 60],
    ["Soft Drinks", "Diet Coke", 80],
    ["Soft Drinks", "Soda", 40],
    ["Soft Drinks", "Mineral Water 1L", 30],

    ["Fresh & Cooling Drinks", "Fresh Lime Water", 50],
    ["Fresh & Cooling Drinks", "Fresh Lime Soda", 70],
    ["Fresh & Cooling Drinks", "Sweet Lime Soda", 70],
    ["Fresh & Cooling Drinks", "Mint Lime Cooler", 90],
    ["Fresh & Cooling Drinks", "Jaljeera", 60],
    ["Fresh & Cooling Drinks", "Aam Panna", 70],
    ["Fresh & Cooling Drinks", "Kokum Cooler", 90],
    ["Fresh & Cooling Drinks", "Watermelon Cooler", 90],
    ["Fresh & Cooling Drinks", "Rose Milk", 80],
    ["Fresh & Cooling Drinks", "Badam Milk", 100],
    ["Fresh & Cooling Drinks", "Tender Coconut Water", 80],

    ["Fresh Juices", "Orange Juice", 100],
    ["Fresh Juices", "Apple Juice", 120],
    ["Fresh Juices", "Pineapple Juice", 100],
    ["Fresh Juices", "Watermelon Juice", 90],
    ["Fresh Juices", "Mosambi Juice", 100],
    ["Fresh Juices", "Pomegranate Juice", 140],
    ["Fresh Juices", "Mango Juice", 110],
    ["Fresh Juices", "Grape Juice", 100],
    ["Fresh Juices", "Carrot Juice", 100],
    ["Fresh Juices", "ABC Juice", 130],
    ["Fresh Juices", "Mixed Fruit Juice", 120],

    ["Lassi & Buttermilk", "Plain Lassi", 80],
    ["Lassi & Buttermilk", "Sweet Lassi", 90],
    ["Lassi & Buttermilk", "Salted Lassi", 90],
    ["Lassi & Buttermilk", "Mango Lassi", 120],
    ["Lassi & Buttermilk", "Rose Lassi", 110],
    ["Lassi & Buttermilk", "Kesar Lassi", 130],
    ["Lassi & Buttermilk", "Dry Fruit Lassi", 150],
    ["Lassi & Buttermilk", "Plain Buttermilk", 50],
    ["Lassi & Buttermilk", "Masala Buttermilk", 60],
    ["Lassi & Buttermilk", "Mint Buttermilk", 70],

    ["Hot Drinks", "Tea", 30],
    ["Hot Drinks", "Masala Tea", 40],
    ["Hot Drinks", "Ginger Tea", 40],
    ["Hot Drinks", "Green Tea", 50],
    ["Hot Drinks", "Lemon Tea", 40],
    ["Hot Drinks", "Black Tea", 40],
    ["Hot Drinks", "Coffee", 50],
    ["Hot Drinks", "Filter Coffee", 60],
    ["Hot Drinks", "Black Coffee", 50],
    ["Hot Drinks", "Hot Chocolate", 100],
    ["Hot Drinks", "Horlicks", 80],
    ["Hot Drinks", "Bournvita", 80],

    ["Cold Coffee", "Cold Coffee", 100],
    ["Cold Coffee", "Cold Coffee with Ice Cream", 130],
    ["Cold Coffee", "Classic Iced Coffee", 110],
    ["Cold Coffee", "Mocha Cold Coffee", 130],
    ["Cold Coffee", "Caramel Cold Coffee", 130],
    ["Cold Coffee", "Chocolate Cold Coffee", 130],

    ["Milkshakes", "Vanilla Shake", 110],
    ["Milkshakes", "Chocolate Shake", 120],
    ["Milkshakes", "Strawberry Shake", 120],
    ["Milkshakes", "Mango Shake", 120],
    ["Milkshakes", "Banana Shake", 110],
    ["Milkshakes", "Butterscotch Shake", 130],
    ["Milkshakes", "Oreo Shake", 140],
    ["Milkshakes", "KitKat Shake", 150],
    ["Milkshakes", "Biscoff Shake", 170],
    ["Milkshakes", "Dry Fruit Shake", 170],

    ["Mocktails", "Virgin Mojito", 120],
    ["Mocktails", "Blue Lagoon", 130],
    ["Mocktails", "Virgin Pina Colada", 140],
    ["Mocktails", "Fruit Punch", 140],
    ["Mocktails", "Watermelon Mojito", 130],
    ["Mocktails", "Green Apple Mojito", 130],
    ["Mocktails", "Strawberry Mojito", 140],
    ["Mocktails", "Mango Mojito", 140],
    ["Mocktails", "Blueberry Mojito", 150],
    ["Mocktails", "Orange Sparkler", 130],
    ["Mocktails", "Tropical Sunset", 150],
    ["Mocktails", "Coconut Colada", 150],

    // NOODLES
    ["Veg Noodles", "Veg Hakka Noodles", 120],
    ["Veg Noodles", "Veg Chow Mein", 120],
    ["Veg Noodles", "Veg Schezwan Noodles", 130],
    ["Veg Noodles", "Veg Chilli Garlic Noodles", 130],
    ["Veg Noodles", "Veg Garlic Noodles", 130],
    ["Veg Noodles", "Veg Hot Garlic Noodles", 140],
    ["Veg Noodles", "Veg Ginger Garlic Noodles", 140],
    ["Veg Noodles", "Veg Manchurian Noodles", 150],
    ["Veg Noodles", "Veg Burnt Garlic Noodles", 150],
    ["Veg Noodles", "Veg Singapore Noodles", 150],
    ["Veg Noodles", "Veg Shanghai Noodles", 150],
    ["Veg Noodles", "Veg Hong Kong Noodles", 160],
    ["Veg Noodles", "Veg Butter Garlic Noodles", 160],
    ["Veg Noodles", "Veg Mushroom Noodles", 160],
    ["Veg Noodles", "Veg Corn Noodles", 150],
    ["Veg Noodles", "Veg Paneer Noodles", 170],
    ["Veg Noodles", "Paneer Schezwan Noodles", 180],
    ["Veg Noodles", "Paneer Chilli Garlic Noodles", 180],
    ["Veg Noodles", "Triple Schezwan Noodles", 190],
    ["Veg Noodles", "American Chopsuey", 180],
    ["Veg Noodles", "Chinese Chopsuey", 190],
    ["Veg Noodles", "Pan Fried Noodles", 190],
    ["Veg Noodles", "Cantonese Noodles", 190],
    ["Veg Noodles", "Thai Noodles", 200],
    ["Veg Noodles", "Malaysian Noodles", 200],

    ["Egg Noodles", "Egg Noodles", 140],
    ["Egg Noodles", "Egg Hakka Noodles", 150],
    ["Egg Noodles", "Egg Schezwan Noodles", 160],
    ["Egg Noodles", "Egg Chilli Garlic Noodles", 160],
    ["Egg Noodles", "Egg Manchurian Noodles", 170],
    ["Egg Noodles", "Egg Burnt Garlic Noodles", 170],
    ["Egg Noodles", "Egg Singapore Noodles", 180],
    ["Egg Noodles", "Triple Egg Noodles", 180],
    ["Egg Noodles", "Triple Egg Schezwan Noodles", 190],

    ["Chicken Noodles", "Chicken Noodles", 180],
    ["Chicken Noodles", "Chicken Hakka Noodles", 190],
    ["Chicken Noodles", "Chicken Schezwan Noodles", 200],
    ["Chicken Noodles", "Chicken Chilli Garlic Noodles", 200],
    ["Chicken Noodles", "Chicken Garlic Noodles", 200],
    ["Chicken Noodles", "Chicken Manchurian Noodles", 210],
    ["Chicken Noodles", "Chicken Burnt Garlic Noodles", 210],
    ["Chicken Noodles", "Chicken Singapore Noodles", 220],
    ["Chicken Noodles", "Chicken Shanghai Noodles", 220],
    ["Chicken Noodles", "Chicken Hong Kong Noodles", 230],
    ["Chicken Noodles", "Chicken Butter Garlic Noodles", 230],
    ["Chicken Noodles", "Chicken Pan Fried Noodles", 240],
    ["Chicken Noodles", "Chicken Cantonese Noodles", 240],
    ["Chicken Noodles", "Chicken Thai Noodles", 250],

    ["Seafood & Special Noodles", "Prawn Hakka Noodles", 220],
    ["Seafood & Special Noodles", "Prawn Schezwan Noodles", 230],
    ["Seafood & Special Noodles", "Prawn Chilli Garlic Noodles", 230],
    ["Seafood & Special Noodles", "Prawn Burnt Garlic Noodles", 240],
    ["Seafood & Special Noodles", "Prawn Singapore Noodles", 250],
    ["Seafood & Special Noodles", "Mixed Noodles", 250],
    ["Seafood & Special Noodles", "Mixed Schezwan Noodles", 260],
    ["Seafood & Special Noodles", "Mixed Chilli Garlic Noodles", 260],
    ["Seafood & Special Noodles", "Mixed Burnt Garlic Noodles", 270],
    ["Seafood & Special Noodles", "Chef Special Noodles", 280],

    // STARTERS
    ["Veg Starters", "Gobi 65", 120],
    ["Veg Starters", "Paneer 65", 150],
    ["Veg Starters", "Baby Corn 65", 140],
    ["Veg Starters", "Mushroom 65", 150],
    ["Veg Starters", "Crispy Corn", 130],
    ["Veg Starters", "Chilli Paneer", 160],
    ["Veg Starters", "Chilli Gobi", 140],
    ["Veg Starters", "Chilli Mushroom", 150],
    ["Veg Starters", "Paneer Majestic", 180],
    ["Veg Starters", "Paneer Pepper Fry", 170],
    ["Veg Starters", "Mushroom Pepper Fry", 160],
    ["Veg Starters", "Baby Corn Manchurian", 150],
    ["Veg Starters", "Gobi Manchurian", 140],
    ["Veg Starters", "Veg Manchurian", 130],
    ["Veg Starters", "Crispy Baby Corn", 150],
    ["Veg Starters", "Masala Papad", 70],
    ["Veg Starters", "Mirchi Bajji", 60],
    ["Veg Starters", "Onion Pakoda", 80],
    ["Veg Starters", "Punugulu", 70],
    ["Veg Starters", "Mysore Bonda", 70],
    ["Veg Starters", "Medu Vada", 60],
    ["Veg Starters", "Banana Bajji", 70],

    ["Non-Veg Starters", "Chicken 65", 180],
    ["Non-Veg Starters", "Chicken 555", 200],
    ["Non-Veg Starters", "Chicken Majestic", 220],
    ["Non-Veg Starters", "Andhra Chicken Fry", 200],
    ["Non-Veg Starters", "Chicken Pepper Fry", 210],
    ["Non-Veg Starters", "Chilli Chicken", 200],
    ["Non-Veg Starters", "Chicken Manchurian", 200],
    ["Non-Veg Starters", "Chicken Lollipop", 220],
    ["Non-Veg Starters", "Chicken Wings", 220],
    ["Non-Veg Starters", "Chicken Pakoda", 190],
    ["Non-Veg Starters", "Kodi Vepudu", 220],
    ["Non-Veg Starters", "Gongura Chicken Fry", 220],
    ["Non-Veg Starters", "Mutton Pepper Fry", 280],
    ["Non-Veg Starters", "Mutton Roast", 300],
    ["Non-Veg Starters", "Mutton Keema Balls", 280],
    ["Non-Veg Starters", "Fish Fry", 220],
    ["Non-Veg Starters", "Apollo Fish", 250],
    ["Non-Veg Starters", "Chilli Fish", 230],
    ["Non-Veg Starters", "Fish 65", 220],
    ["Non-Veg Starters", "Prawn Fry", 280],
    ["Non-Veg Starters", "Chilli Prawns", 280],
    ["Non-Veg Starters", "Prawn 65", 280],
    ["Non-Veg Starters", "Prawn Pepper Fry", 300],
    ["Non-Veg Starters", "Squid Fry", 280],

    ["Andhra/Telangana Special Starters", "Chicken Pakodi", 180],
    ["Andhra/Telangana Special Starters", "Kodi Vepudu", 220],
    ["Andhra/Telangana Special Starters", "Andhra Chicken Fry", 200],
    ["Andhra/Telangana Special Starters", "Gongura Chicken", 220],
    ["Andhra/Telangana Special Starters", "Natukodi Fry", 280],
    ["Andhra/Telangana Special Starters", "Royyala Vepudu", 300],
    ["Andhra/Telangana Special Starters", "Royyala Iguru", 300],
    ["Andhra/Telangana Special Starters", "Chepala Vepudu", 220],
    ["Andhra/Telangana Special Starters", "Mirapakaya Kodi", 220],
    ["Andhra/Telangana Special Starters", "Gongura Mutton", 320],
    ["Andhra/Telangana Special Starters", "Mutton Sukka", 300],
    ["Andhra/Telangana Special Starters", "Chicken Sukka", 220],
    ["Andhra/Telangana Special Starters", "Ragi Sangati Chicken Combo", 280],

    // MAIN COURSE
    ["Veg Curries", "Paneer Butter Masala", 220],
    ["Veg Curries", "Kadai Paneer", 220],
    ["Veg Curries", "Palak Paneer", 210],
    ["Veg Curries", "Paneer Tikka Masala", 240],
    ["Veg Curries", "Shahi Paneer", 230],
    ["Veg Curries", "Malai Kofta", 220],
    ["Veg Curries", "Mix Veg Curry", 190],
    ["Veg Curries", "Veg Kolhapuri", 200],
    ["Veg Curries", "Kadai Mushroom", 210],
    ["Veg Curries", "Mushroom Masala", 210],
    ["Veg Curries", "Aloo Gobi Masala", 180],
    ["Veg Curries", "Chana Masala", 170],
    ["Veg Curries", "Dal Fry", 150],
    ["Veg Curries", "Dal Tadka", 160],
    ["Veg Curries", "Dal Makhani", 180],

    ["Chicken Curries", "Butter Chicken", 280],
    ["Chicken Curries", "Kadai Chicken", 280],
    ["Chicken Curries", "Chicken Curry", 260],
    ["Chicken Curries", "Chicken Masala", 270],
    ["Chicken Curries", "Chicken Tikka Masala", 290],
    ["Chicken Curries", "Chicken Handi", 280],
    ["Chicken Curries", "Chicken Chettinad", 290],
    ["Chicken Curries", "Chicken Lababdar", 300],
    ["Chicken Curries", "Andhra Chicken Curry", 280],
    ["Chicken Curries", "Chicken Kolhapuri", 290],
    ["Chicken Curries", "Chicken Rara", 310],

    ["Mutton Curries", "Mutton Curry", 350],
    ["Mutton Curries", "Mutton Masala", 360],
    ["Mutton Curries", "Mutton Rogan Josh", 380],
    ["Mutton Curries", "Mutton Kadai", 370],
    ["Mutton Curries", "Mutton Handi", 380],
    ["Mutton Curries", "Mutton Keema", 360],
    ["Mutton Curries", "Andhra Mutton Curry", 370],
    ["Mutton Curries", "Mutton Fry", 390],

    ["Fish & Prawns", "Fish Curry", 280],
    ["Fish & Prawns", "Fish Masala", 300],
    ["Fish & Prawns", "Andhra Fish Curry", 300],
    ["Fish & Prawns", "Fish Fry", 320],
    ["Fish & Prawns", "Fish Tikka Masala", 330],
    ["Fish & Prawns", "Prawns Curry", 340],
    ["Fish & Prawns", "Prawns Masala", 350],
    ["Fish & Prawns", "Prawns Fry", 370],
    ["Fish & Prawns", "Prawns Kadai", 360],

    ["Rice", "Steamed Rice", 100],
    ["Rice", "Jeera Rice", 130],
    ["Rice", "Ghee Rice", 150],
    ["Rice", "Veg Pulao", 160],
    ["Rice", "Peas Pulao", 160],
    ["Rice", "Kaju Rice", 190],
    ["Rice", "Lemon Rice", 120],
    ["Rice", "Tomato Rice", 120],
    ["Rice", "Curd Rice", 100],

    ["Main Course Biryani", "Veg Biryani", 200],
    ["Main Course Biryani", "Paneer Biryani", 220],
    ["Main Course Biryani", "Mushroom Biryani", 220],
    ["Main Course Biryani", "Kaju Biryani", 240],
    ["Main Course Biryani", "Egg Biryani", 220],
    ["Main Course Biryani", "Chicken Biryani", 280],
    ["Main Course Biryani", "Chicken 65 Biryani", 300],
    ["Main Course Biryani", "Special Chicken Biryani", 330],
    ["Main Course Biryani", "Mutton Biryani", 380],
    ["Main Course Biryani", "Fish Biryani", 350],
    ["Main Course Biryani", "Prawns Biryani", 360],

    ["Fried Rice", "Veg Fried Rice", 170],
    ["Fried Rice", "Paneer Fried Rice", 200],
    ["Fried Rice", "Mushroom Fried Rice", 200],
    ["Fried Rice", "Schezwan Fried Rice", 190],
    ["Fried Rice", "Egg Fried Rice", 190],
    ["Fried Rice", "Chicken Fried Rice", 230],
    ["Fried Rice", "Chicken Schezwan Fried Rice", 250],
    ["Fried Rice", "Prawns Fried Rice", 280],
    ["Fried Rice", "Mixed Fried Rice", 300],

    ["Main Course Noodles", "Veg Hakka Noodles", 170],
    ["Main Course Noodles", "Veg Schezwan Noodles", 190],
    ["Main Course Noodles", "Paneer Noodles", 200],
    ["Main Course Noodles", "Mushroom Noodles", 200],
    ["Main Course Noodles", "Egg Noodles", 190],
    ["Main Course Noodles", "Chicken Hakka Noodles", 230],
    ["Main Course Noodles", "Chicken Schezwan Noodles", 250],
    ["Main Course Noodles", "Prawns Noodles", 280],
    ["Main Course Noodles", "Mixed Noodles", 300],

    ["Indian Breads", "Plain Roti", 30],
    ["Indian Breads", "Butter Roti", 40],
    ["Indian Breads", "Plain Naan", 50],
    ["Indian Breads", "Butter Naan", 60],
    ["Indian Breads", "Garlic Naan", 70],
    ["Indian Breads", "Tandoori Roti", 35],
    ["Indian Breads", "Butter Kulcha", 60],
    ["Indian Breads", "Aloo Paratha", 80],
    ["Indian Breads", "Paneer Paratha", 100],
    ["Indian Breads", "Lachha Paratha", 70],

    ["Thali / Combos", "Veg Thali", 220],
    ["Thali / Combos", "Special Veg Thali", 280],
    ["Thali / Combos", "North Indian Thali", 260],
    ["Thali / Combos", "South Indian Meals", 180],
    ["Thali / Combos", "Chicken Thali", 320],
    ["Thali / Combos", "Special Non-Veg Thali", 380],
    ["Thali / Combos", "Chicken Biryani Combo", 330],
    ["Thali / Combos", "Paneer Meal Combo", 280]
];

db.exec("DELETE FROM foods");

const insert = db.prepare(`
    INSERT INTO foods
    (name, category, price, description, image, available)
    VALUES (?, ?, ?, ?, ?, 1)
`);

for (const food of foods) {
    insert.run(
        food[1],
        food[0],
        food[2],
        `Delicious ${food[1]} prepared fresh for you.`,
        ""
    );
}

console.log("=================================");
console.log("FoodHub Menu Loaded Successfully");
console.log("Total items:", foods.length);
console.log("=================================");

db.close();